"""Repository interfaces for the Wave 1 control plane.

No implementation lives here except fakes.py's in-memory versions, used by
this wave's own tests and by later waves until a real Supabase-backed
implementation is wired in. Nothing here touches live credentials.
"""
from typing import Optional, Protocol

from backend.control_plane.models import (
    Action,
    ApprovalRequest,
    Artifact,
    BudgetReservation,
    Run,
    RunEvent,
    RunStep,
)


class RunRepository(Protocol):
    def create(self, run: Run) -> Run: ...
    def get(self, run_id: str) -> Optional[Run]: ...
    def update_status(self, run_id: str, status: str, *, error: Optional[str] = None) -> None: ...


class RunStepRepository(Protocol):
    def create_attempt(self, step: RunStep) -> RunStep:
        """Create a new attempt row. If (run_id, step_key) already has attempts,
        the caller is responsible for setting attempt_number = max(existing) + 1."""
        ...

    def get_latest_attempt(self, run_id: str, step_key: str) -> Optional[RunStep]: ...
    def list_attempts(self, run_id: str, step_key: str) -> list[RunStep]: ...
    def update_status(self, step_id: str, status: str, *, error: Optional[str] = None) -> None: ...


class ActionRepository(Protocol):
    def create(self, action: Action) -> Action: ...
    def get(self, action_id: str) -> Optional[Action]: ...
    def get_by_idempotency_key(self, idempotency_key: str) -> Optional[Action]: ...
    def update_status(self, action_id: str, status: str) -> None: ...


class ApprovalRequestRepository(Protocol):
    def create(self, request: ApprovalRequest) -> ApprovalRequest: ...
    def get(self, request_id: str) -> Optional[ApprovalRequest]: ...
    def get_pending_for_gate(self, run_id: str, gate_key: str) -> list[ApprovalRequest]: ...
    def decide(self, request_id: str, status: str, *, decided_by: str, note: Optional[str] = None) -> ApprovalRequest: ...


class RunEventRepository(Protocol):
    def append(self, run_id: str, event_type: str, payload: dict) -> int:
        """Atomically assign and return the next sequence for run_id."""
        ...

    def list_since(self, run_id: str, after_sequence: int = 0) -> list[RunEvent]: ...


class ArtifactRepository(Protocol):
    def upsert(self, artifact: Artifact) -> Artifact: ...
    def list_for_run(self, run_id: str) -> list[Artifact]: ...


class BudgetReservationRepository(Protocol):
    def reserve(self, reservation: BudgetReservation) -> BudgetReservation: ...
    def get(self, reservation_id: str) -> Optional[BudgetReservation]: ...
    def commit(self, reservation_id: str, actual_usd: float) -> None: ...
    def release(self, reservation_id: str) -> None: ...
    def list_expired(self, *, now: Optional[str] = None) -> list[BudgetReservation]: ...
