"""Repository interfaces for the Wave 1 control plane.

No implementation lives here except fakes.py's in-memory versions, used by
this wave's own tests and by later waves until a real Supabase-backed
implementation is wired in. Nothing here touches live credentials.
"""
from typing import Optional, Protocol

from backend.control_plane.models import (
    Action,
    ActionReceipt,
    ApprovalRequest,
    Artifact,
    BrainAcl,
    BrainRecord,
    BudgetReservation,
    BudgetReservationLedger,
    LegacyRetirementCheck,
    RolloutCampaign,
    RolloutEvidence,
    Run,
    RunEvent,
    RunStep,
)


class RunRepository(Protocol):
    def create(self, run: Run) -> Run: ...
    def get(self, run_id: str) -> Optional[Run]: ...
    def update_status(self, run_id: str, status: str, *, error: Optional[str] = None) -> None: ...


class RunStepRepository(Protocol):
    def create_attempt(self, step: RunStep) -> RunStep:
        """Create a new attempt row. If (run_id, step_key) already has attempts,
        the caller is responsible for setting attempt_number = max(existing) + 1."""
        ...

    def get_latest_attempt(self, run_id: str, step_key: str) -> Optional[RunStep]: ...
    def list_attempts(self, run_id: str, step_key: str) -> list[RunStep]: ...
    def update_status(self, step_id: str, status: str, *, error: Optional[str] = None) -> None: ...
    def update_fields(self, step_id: str, patch: dict[str, object]) -> None: ...


class ActionRepository(Protocol):
    def create(self, action: Action) -> Action: ...
    def get(self, action_id: str) -> Optional[Action]: ...
    def get_by_idempotency_key(self, idempotency_key: str) -> Optional[Action]: ...
    def update_status(self, action_id: str, status: str) -> None: ...


class ApprovalRequestRepository(Protocol):
    def create(self, request: ApprovalRequest) -> ApprovalRequest: ...
    def get(self, request_id: str) -> Optional[ApprovalRequest]: ...
    def get_pending_for_gate(self, run_id: str, gate_key: str) -> list[ApprovalRequest]: ...
    def decide(self, request_id: str, status: str, *, decided_by: str, note: Optional[str] = None) -> ApprovalRequest: ...
    def consume(
        self,
        request_id: str,
        *,
        expected_action_digest: str,
        expected_policy_version: str,
    ) -> ApprovalRequest: ...


class RunEventRepository(Protocol):
    def append(self, run_id: str, event_type: str, payload: dict) -> int:
        """Atomically assign and return the next sequence for run_id."""
        ...

    def list_since(self, run_id: str, after_sequence: int = 0) -> list[RunEvent]: ...


class ArtifactRepository(Protocol):
    def upsert(self, artifact: Artifact) -> Artifact: ...
    def list_for_run(self, run_id: str) -> list[Artifact]: ...


class ActionReceiptRepository(Protocol):
    def create(self, receipt: ActionReceipt) -> ActionReceipt: ...
    def get_by_action_id(self, action_id: str) -> Optional[ActionReceipt]: ...
    def get_by_idempotency_key(self, idempotency_key: str) -> Optional[ActionReceipt]: ...
    def update_collision_status(self, receipt_id: str, collision_status: str) -> None: ...


class BudgetReservationRepository(Protocol):
    def reserve(
        self,
        reservation: BudgetReservation,
        *,
        founder_id: Optional[str] = None,
        reserved_credits: Optional[int] = None,
        markup: float = 10.0,
    ) -> BudgetReservation: ...
    def get(self, reservation_id: str) -> Optional[BudgetReservation]: ...
    def get_ledger(self, reservation_id: str) -> Optional[BudgetReservationLedger]: ...
    def sum_reserved_credits(self, founder_id: str, *, exclude_reservation_id: Optional[str] = None) -> int: ...
    def commit(
        self,
        reservation_id: str,
        actual_usd: float,
        *,
        billed_credits: int = 0,
        overspend_usd: float = 0.0,
        unreconciled_credits: int = 0,
        reconciliation_error: Optional[str] = None,
    ) -> None: ...
    def release(self, reservation_id: str) -> None: ...
    def expire(self, reservation_id: str) -> None: ...
    def list_expired(self, *, now: Optional[str] = None) -> list[BudgetReservation]: ...


class BrainRecordRepository(Protocol):
    def create(self, record: BrainRecord) -> BrainRecord: ...
    def get(self, record_id: str) -> Optional[BrainRecord]: ...
    def list_by_company(self, company_id: str, *, include_tombstoned: bool = False) -> list[BrainRecord]: ...
    def list_by_external_id(self, company_id: str, source: str, external_id: str) -> list[BrainRecord]: ...
    def list_by_ids(self, record_ids: list[str]) -> list[BrainRecord]: ...
    def search_content(self, company_id: str, query: str, limit: int = 10) -> list[BrainRecord]: ...
    def mark_superseded(self, old_record_id: str, new_record_id: str) -> None: ...
    def mark_tombstone(self, record_id: str) -> None: ...


class BrainAclRepository(Protocol):
    def create(self, acl: BrainAcl) -> BrainAcl: ...
    def list_for_record(self, record_id: str) -> list[BrainAcl]: ...
    def has_access(self, record_id: str, caller_role: str, caller_user_id: Optional[str] = None) -> bool: ...
    def delete_for_record(self, record_id: str) -> None: ...


class RolloutCampaignRepository(Protocol):
    def create(self, campaign: RolloutCampaign) -> RolloutCampaign: ...
    def get_active(self, feature: str) -> Optional[RolloutCampaign]: ...
    def update(self, campaign_id: str, patch: dict[str, object]) -> Optional[RolloutCampaign]: ...


class RolloutEvidenceRepository(Protocol):
    def create(self, evidence: RolloutEvidence) -> RolloutEvidence: ...
    def list_for_campaign(self, campaign_id: str) -> list[RolloutEvidence]: ...


class LegacyRetirementCheckRepository(Protocol):
    def upsert(self, check: LegacyRetirementCheck) -> LegacyRetirementCheck: ...
    def get(self, feature: str) -> Optional[LegacyRetirementCheck]: ...
